version: '3.7'
services:

  jenkins:
    image: jenkins.nginx.docker:lts
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: false
    ports:
      - '2022:22'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - "/dev/vboxdrv:/dev/vboxdrv"
    environment:
      - UID_JENKINS=${UID_JENKINS:-1000}
      - GID_JENKINS=${GID_JENKINS:-1000}
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: false
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
#      - ${NGINX_SSL_CERT:-./certs/self_signed_cert.pem}:/etc/nginx/ssl/server.crt:ro # uncomment for SSL
#      - ${NGINX_SSL_KEY:-./certs/self_signed_key.pem}:/etc/nginx/ssl/server.key:ro   # uncomment for SSL
    restart: always
